### ISSUE TITLE
Manage database deletion collector for jest test

### ISSUE THREAD

**Issue by victorbillaud** [victorbillaud/tomato#44]

**Comment by victorbillaud** [comment]
```py
def setup_test_schema():
    """Set up a test schema in the database replicating the public schema using Supabase CLI"""
    dump_file = "supabase/public_schema_dump.sql"
    test_schema_file = "supabase/test_schema.sql"

    # Dump the public schema
    with open(dump_file, "w") as file:
        subprocess.run(
            ["supabase", "db", "dump", "--local", "--schema", "public"], stdout=file
        )

    # Read the dump and replace 'public' with 'test'
    with open(dump_file, "r") as file:
        schema_sql = file.read().replace("public", "test")

    with open(test_schema_file, "w") as file:
        file.write(schema_sql)

    docker_container_name = "supabase_db_tomato"

    # Execute the modified dump to create the test schema within the Docker container
    try:
        subprocess.run(
            [
                "docker",
                "exec",
                "-i",
                docker_container_name,
                "psql",
                "-U",
                os.environ.get("SUPABASE_DB_USER", "postgres"),
                "-d",
                "postgres",
                "-f",
                "-",
            ],  # Read SQL from stdin
            input=open(test_schema_file, "rb").read(),
            check=True,
        )
    except FileNotFoundError:
        print("Docker is not found. Please ensure Docker is installed.")
        sys.exit(1)
    except subprocess.CalledProcessError as e:
        print(f"Error executing command in Docker container: {e}")
        sys.exit(1)
    except KeyError as e:
        print(f"Environment variable not set: {e}")
        sys.exit(1)

    # Clean up
    os.remove(dump_file)
    os.remove(test_schema_file)
    print("Test schema set up successfully.")
```

**Comment by victorbillaud** [comment]
Le probleme c'est que apres c'est impossible d'utiliser le schema depuis le client js
```
❯ pnpm run test                                                                                      ─╯

> @ test /Users/victorbillaud/dev/ext-efrei/tomato/utils
> jest

watchman warning:  Recrawled this watch 37 times, most recently because:
MustScanSubDirs UserDroppedTo resolve, please review the information on
https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
To clear this warning, run:
`watchman watch-del '/Users/victorbillaud/dev/ext-efrei/tomato' ; watchman watch-project '/Users/victorbillaud/dev/ext-efrei/tomato'`

Error: Jest: Got error running globalSetup - /Users/victorbillaud/dev/ext-efrei/tomato/utils/lib/jest/setup.ts, reason: [TSError: lib/jest/setup.ts:9:26 - error TS2345: Argument of type 'SupabaseClient<Database, "test", "test">' is not assignable to parameter of type 'SupabaseClient<Database, "public", { Tables: { item: { Row: { activated: boolean; created_at: string; description: string; id: string; lost: boolean; lost_at: string; name: string; notify_anyway: boolean; qrcode_id: string; user_id: string; }; Insert: { ...; }; Update: { ...; }; Relationships: [...]; }; profiles: { ...'.
  Type '"test"' is not assignable to type '"public"'.

9     await createFakeUser(sp);
                           ~~
lib/jest/setup.ts:10:52 - error TS2345: Argument of type 'SupabaseClient<Database, "test", "test">' is not assignable to parameter of type 'SupabaseClient<Database, "public", { Tables: { item: { Row: { activated: boolean; created_at: string; description: string; id: string; lost: boolean; lost_at: string; name: string; notify_anyway: boolean; qrcode_id: string; user_id: string; }; Insert: { ...; }; Update: { ...; }; Relationships: [...]; }; profiles: { ...'.

10     const { user, session } = await signInFakeUser(sp);
                                                      ~~]
    at runGlobalHook (/Users/victorbillaud/dev/ext-efrei/tomato/utils/node_modules/.pnpm/@jest+core@29.7.0_ts-node@10.9.1/node_modules/@jest/core/build/runGlobalHook.js:124:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runJest (/Users/victorbillaud/dev/ext-efrei/tomato/utils/node_modules/.pnpm/@jest+core@29.7.0_ts-node@10.9.1/node_modules/@jest/core/build/runJest.js:327:5)
    at async _run10000 (/Users/victorbillaud/dev/ext-efrei/tomato/utils/node_modules/.pnpm/@jest+core@29.7.0_ts-node@10.9.1/node_modules/@jest/core/build/cli/index.js:343:7)
    at async runCLI (/Users/victorbillaud/dev/ext-efrei/tomato/utils/node_modules/.pnpm/@jest+core@29.7.0_ts-node@10.9.1/node_modules/@jest/core/build/cli/index.js:198:3)
    at async Object.run (/Users/victorbillaud/dev/ext-efrei/tomato/utils/node_modules/.pnpm/jest-cli@29.7.0_@types+node@20.10.3_ts-node@10.9.1/node_modules/jest-cli/build/run.js:130:37)
 ELIFECYCLE  Test failed. See above for more details.
```

**Comment by victorbillaud** [comment]
Je pense que c'est à cause du schema auth supabase qui n'est pas bien attribué à test
